DECLARE
	R ORDERS%ROWTYPE;
	SID NUMBER;
BEGIN
	FOR R IN (SELECT * FROM ORDERS) 
	LOOP 
		SELECT SHOP_ID INTO SID FROM PRODUCTS WHERE PRODUCT_ID = R.PRODUCT_ID;
		IF R.DELIVERY_STATUS<> 'CANCELLED' THEN
			DBMS_OUTPUT.PUT_LINE('Order ID: ' || R.ORDER_ID || ' Product ID: ' || R.PRODUCT_ID || ' Shop ID: ' || SID);
			UPDATE SELLER_USER SET TOTAL_REVENUE = TOTAL_REVENUE + R.TOTAL_PRICE WHERE SHOP_ID = SID;

		END IF;
	END LOOP;

END ;
/